name: Type Checking ğŸ”°

on:
  push:
    branches:
      - main
    paths:
      - 'black_knight/**/*.py'

jobs:
  mypy:
    name: run MyPy ğŸ
    runs-on: ubuntu-latest
    steps:
      - run: echo 'test!'
